language: node_js
node_js:
    - "node"

sudo: false

cache:
    directories:
        - $HOME/.cache/bower
        - $HOME/.npm
    
before_script:
    - npm install -g gulp bower
    - bower install

script: gulp

notifications:
    email: false